// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace emp.maersk.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class datedSchedule : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"datedSchedule\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"" +
				"name\":\"scheduleEntries\",\"type\":{\"type\":\"record\",\"name\":\"scheduleEntries\",\"namesp" +
				"ace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"scheduleEntry\",\"type\":{\"type\":\"array\",\"" +
				"items\":{\"type\":\"record\",\"name\":\"scheduleEntry_record\",\"namespace\":\"emp.maersk.co" +
				"m\",\"fields\":[{\"name\":\"rotationId\",\"type\":\"string\"},{\"name\":\"rotationName\",\"type\"" +
				":\"string\"},{\"name\":\"rotationVersion\",\"type\":\"string\"},{\"name\":\"scheduleEntryID\"," +
				"\"type\":{\"type\":\"record\",\"name\":\"scheduleEntryID\",\"namespace\":\"emp.maersk.com\",\"f" +
				"ields\":[{\"name\":\"scheduleEntryKey\",\"type\":\"string\"},{\"name\":\"scheduleEntryIdenti" +
				"fier\",\"type\":{\"type\":\"record\",\"name\":\"scheduleEntryIdentifier\",\"namespace\":\"emp." +
				"maersk.com\",\"fields\":[{\"name\":\"vessel\",\"type\":{\"type\":\"record\",\"name\":\"vessel\",\"" +
				"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"vesselCode\",\"type\":\"string\"},{\"na" +
				"me\":\"IMONumber\",\"type\":\"string\"},{\"name\":\"vesselName\",\"type\":\"string\"},{\"name\":\"" +
				"vesselOperatorCode\",\"type\":\"string\"},{\"name\":\"vesselFlag\",\"type\":\"string\"},{\"nam" +
				"e\":\"vesselCallSign\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.vessel\"}},{" +
				"\"name\":\"arrivalVoyage\",\"type\":{\"type\":\"record\",\"name\":\"arrivalVoyage\",\"namespace" +
				"\":\"emp.maersk.com\",\"fields\":[{\"name\":\"voyage\",\"type\":\"string\"},{\"name\":\"directio" +
				"n\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.arrivalVoyage\"}},{\"name\":\"de" +
				"partureVoyage\",\"type\":{\"type\":\"record\",\"name\":\"departureVoyage\",\"namespace\":\"emp" +
				".maersk.com\",\"fields\":[{\"name\":\"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"ty" +
				"pe\":\"string\"}],\"connect.name\":\"emp.maersk.com.departureVoyage\"}},{\"name\":\"arriva" +
				"lService\",\"type\":{\"type\":\"record\",\"name\":\"arrivalService\",\"namespace\":\"emp.maers" +
				"k.com\",\"fields\":[{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"}" +
				",{\"name\":\"transportMode\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.arriva" +
				"lService\"}},{\"name\":\"departureService\",\"type\":{\"type\":\"record\",\"name\":\"departure" +
				"Service\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"code\",\"type\":\"string\"}," +
				"{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"transportMode\",\"type\":\"string\"}],\"conne" +
				"ct.name\":\"emp.maersk.com.departureService\"}},{\"name\":\"previousPortCall\",\"type\":{" +
				"\"type\":\"record\",\"name\":\"previousPortCall\",\"namespace\":\"emp.maersk.com\",\"fields\":" +
				"[{\"name\":\"cityCode\",\"type\":\"string\"},{\"name\":\"terminalCode\",\"type\":\"string\"},{\"n" +
				"ame\":\"cityName\",\"type\":\"string\"},{\"name\":\"terminalName\",\"type\":\"string\"},{\"name\"" +
				":\"cityGeoCode\",\"type\":\"string\"},{\"name\":\"terminalGeoCode\",\"type\":\"string\"},{\"nam" +
				"e\":\"previousScheduleEntryKey\",\"type\":\"string\"},{\"name\":\"arrivalVoyage\",\"type\":\"s" +
				"tring\"},{\"name\":\"departureVoyage\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.c" +
				"om.previousPortCall\"}},{\"name\":\"currentPortCall\",\"type\":{\"type\":\"record\",\"name\":" +
				"\"currentPortCall\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"cityCode\",\"typ" +
				"e\":\"string\"},{\"name\":\"terminalCode\",\"type\":\"string\"},{\"name\":\"cityName\",\"type\":\"" +
				"string\"},{\"name\":\"terminalName\",\"type\":\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"s" +
				"tring\"},{\"name\":\"terminalGeoCode\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.c" +
				"om.currentPortCall\"}},{\"name\":\"nextPortCall\",\"type\":{\"type\":\"record\",\"name\":\"nex" +
				"tPortCall\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"cityCode\",\"type\":\"str" +
				"ing\"},{\"name\":\"terminalCode\",\"type\":\"string\"},{\"name\":\"cityName\",\"type\":\"string\"" +
				"},{\"name\":\"terminalName\",\"type\":\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"string\"}" +
				",{\"name\":\"terminalGeoCode\",\"type\":\"string\"},{\"name\":\"nextScheduleEntryKey\",\"type" +
				"\":\"string\"},{\"name\":\"arrivalVoyage\",\"type\":\"string\"},{\"name\":\"departureVoyage\",\"" +
				"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.nextPortCall\"}}],\"connect.name\":" +
				"\"emp.maersk.com.scheduleEntryIdentifier\"}}],\"connect.name\":\"emp.maersk.com.sched" +
				"uleEntryID\"}},{\"name\":\"arrivalStatus\",\"type\":\"string\"},{\"name\":\"departureStatus\"" +
				",\"type\":\"string\"},{\"name\":\"siteCallStatus\",\"type\":\"string\"},{\"name\":\"pH1\",\"type\"" +
				":\"string\"},{\"name\":\"pH2\",\"type\":\"string\"},{\"name\":\"schedule\",\"type\":{\"type\":\"rec" +
				"ord\",\"name\":\"schedule\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"proformaA" +
				"rrival\",\"type\":\"string\"},{\"name\":\"proformaDeparture\",\"type\":\"string\"},{\"name\":\"s" +
				"cheduledArrival\",\"type\":\"string\"},{\"name\":\"scheduledDeparture\",\"type\":\"string\"}]" +
				",\"connect.name\":\"emp.maersk.com.schedule\"}},{\"name\":\"dummyCall\",\"type\":\"string\"}" +
				",{\"name\":\"omitReason\",\"type\":\"string\"},{\"name\":\"actual\",\"type\":{\"type\":\"record\"," +
				"\"name\":\"actual\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"actualArrival\",\"" +
				"type\":\"string\"},{\"name\":\"actualDeparture\",\"type\":\"string\"},{\"name\":\"arrivalAtPil" +
				"otStation\",\"type\":\"string\"},{\"name\":\"firstPilotOnBoard\",\"type\":\"string\"},{\"name\"" +
				":\"pilotOff\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.actual\"}},{\"name\":\"" +
				"notes\",\"type\":\"string\"},{\"name\":\"updatedBy\",\"type\":\"string\"}],\"connect.name\":\"em" +
				"p.maersk.com.scheduleEntry_record\"}}}],\"connect.name\":\"emp.maersk.com.scheduleEn" +
				"tries\"}}],\"connect.name\":\"emp.maersk.com.datedSchedule\",\"connect.version\":1}");
		private emp.maersk.com.scheduleEntries _scheduleEntries;
		public virtual Schema Schema
		{
			get
			{
				return datedSchedule._SCHEMA;
			}
		}
		public emp.maersk.com.scheduleEntries scheduleEntries
		{
			get
			{
				return this._scheduleEntries;
			}
			set
			{
				this._scheduleEntries = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.scheduleEntries;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.scheduleEntries = (emp.maersk.com.scheduleEntries)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
