// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace emp.maersk.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class departureVoyage : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"departureVoyage\",\"namespace\":\"emp.maersk.com\",\"fields\":[" +
				"{\"name\":\"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"type\":\"string\"}],\"connect" +
				".name\":\"emp.maersk.com.departureVoyage\"}");
		private string _voyage;
		private string _direction;
		public virtual Schema Schema
		{
			get
			{
				return departureVoyage._SCHEMA;
			}
		}
		public string voyage
		{
			get
			{
				return this._voyage;
			}
			set
			{
				this._voyage = value;
			}
		}
		public string direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				this._direction = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.voyage;
			case 1: return this.direction;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.voyage = (System.String)fieldValue; break;
			case 1: this.direction = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
