// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace emp.maersk.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class KeySchema : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"KeySchema\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name" +
				"\":\"messageKey\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.KeySchema\",\"conn" +
				"ect.version\":1}");
		private string _messageKey;
		public virtual Schema Schema
		{
			get
			{
				return KeySchema._SCHEMA;
			}
		}
		public string messageKey
		{
			get
			{
				return this._messageKey;
			}
			set
			{
				this._messageKey = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.messageKey;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.messageKey = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
