// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace emp.maersk.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class schedule : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""schedule"",""namespace"":""emp.maersk.com"",""fields"":[{""name"":""proformaArrival"",""type"":""string""},{""name"":""proformaDeparture"",""type"":""string""},{""name"":""scheduledArrival"",""type"":""string""},{""name"":""scheduledDeparture"",""type"":""string""}],""connect.name"":""emp.maersk.com.schedule""}");
		private string _proformaArrival;
		private string _proformaDeparture;
		private string _scheduledArrival;
		private string _scheduledDeparture;
		public virtual Schema Schema
		{
			get
			{
				return schedule._SCHEMA;
			}
		}
		public string proformaArrival
		{
			get
			{
				return this._proformaArrival;
			}
			set
			{
				this._proformaArrival = value;
			}
		}
		public string proformaDeparture
		{
			get
			{
				return this._proformaDeparture;
			}
			set
			{
				this._proformaDeparture = value;
			}
		}
		public string scheduledArrival
		{
			get
			{
				return this._scheduledArrival;
			}
			set
			{
				this._scheduledArrival = value;
			}
		}
		public string scheduledDeparture
		{
			get
			{
				return this._scheduledDeparture;
			}
			set
			{
				this._scheduledDeparture = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.proformaArrival;
			case 1: return this.proformaDeparture;
			case 2: return this.scheduledArrival;
			case 3: return this.scheduledDeparture;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.proformaArrival = (System.String)fieldValue; break;
			case 1: this.proformaDeparture = (System.String)fieldValue; break;
			case 2: this.scheduledArrival = (System.String)fieldValue; break;
			case 3: this.scheduledDeparture = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
