// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace emp.maersk.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class scheduleEntryIdentifier : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"scheduleEntryIdentifier\",\"namespace\":\"emp.maersk.com\",\"f" +
				"ields\":[{\"name\":\"vessel\",\"type\":{\"type\":\"record\",\"name\":\"vessel\",\"namespace\":\"em" +
				"p.maersk.com\",\"fields\":[{\"name\":\"vesselCode\",\"type\":\"string\"},{\"name\":\"IMONumber" +
				"\",\"type\":\"string\"},{\"name\":\"vesselName\",\"type\":\"string\"},{\"name\":\"vesselOperator" +
				"Code\",\"type\":\"string\"},{\"name\":\"vesselFlag\",\"type\":\"string\"},{\"name\":\"vesselCall" +
				"Sign\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.vessel\"}},{\"name\":\"arriva" +
				"lVoyage\",\"type\":{\"type\":\"record\",\"name\":\"arrivalVoyage\",\"namespace\":\"emp.maersk." +
				"com\",\"fields\":[{\"name\":\"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"type\":\"str" +
				"ing\"}],\"connect.name\":\"emp.maersk.com.arrivalVoyage\"}},{\"name\":\"departureVoyage\"" +
				",\"type\":{\"type\":\"record\",\"name\":\"departureVoyage\",\"namespace\":\"emp.maersk.com\",\"" +
				"fields\":[{\"name\":\"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"type\":\"string\"}]" +
				",\"connect.name\":\"emp.maersk.com.departureVoyage\"}},{\"name\":\"arrivalService\",\"typ" +
				"e\":{\"type\":\"record\",\"name\":\"arrivalService\",\"namespace\":\"emp.maersk.com\",\"fields" +
				"\":[{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"tran" +
				"sportMode\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.arrivalService\"}},{\"" +
				"name\":\"departureService\",\"type\":{\"type\":\"record\",\"name\":\"departureService\",\"name" +
				"space\":\"emp.maersk.com\",\"fields\":[{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"name\"" +
				",\"type\":\"string\"},{\"name\":\"transportMode\",\"type\":\"string\"}],\"connect.name\":\"emp." +
				"maersk.com.departureService\"}},{\"name\":\"previousPortCall\",\"type\":{\"type\":\"record" +
				"\",\"name\":\"previousPortCall\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"city" +
				"Code\",\"type\":\"string\"},{\"name\":\"terminalCode\",\"type\":\"string\"},{\"name\":\"cityName" +
				"\",\"type\":\"string\"},{\"name\":\"terminalName\",\"type\":\"string\"},{\"name\":\"cityGeoCode\"" +
				",\"type\":\"string\"},{\"name\":\"terminalGeoCode\",\"type\":\"string\"},{\"name\":\"previousSc" +
				"heduleEntryKey\",\"type\":\"string\"},{\"name\":\"arrivalVoyage\",\"type\":\"string\"},{\"name" +
				"\":\"departureVoyage\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.previousPor" +
				"tCall\"}},{\"name\":\"currentPortCall\",\"type\":{\"type\":\"record\",\"name\":\"currentPortCa" +
				"ll\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"cityCode\",\"type\":\"string\"},{" +
				"\"name\":\"terminalCode\",\"type\":\"string\"},{\"name\":\"cityName\",\"type\":\"string\"},{\"nam" +
				"e\":\"terminalName\",\"type\":\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"string\"},{\"name" +
				"\":\"terminalGeoCode\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.currentPort" +
				"Call\"}},{\"name\":\"nextPortCall\",\"type\":{\"type\":\"record\",\"name\":\"nextPortCall\",\"na" +
				"mespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"cityCode\",\"type\":\"string\"},{\"name\":" +
				"\"terminalCode\",\"type\":\"string\"},{\"name\":\"cityName\",\"type\":\"string\"},{\"name\":\"ter" +
				"minalName\",\"type\":\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"string\"},{\"name\":\"term" +
				"inalGeoCode\",\"type\":\"string\"},{\"name\":\"nextScheduleEntryKey\",\"type\":\"string\"},{\"" +
				"name\":\"arrivalVoyage\",\"type\":\"string\"},{\"name\":\"departureVoyage\",\"type\":\"string\"" +
				"}],\"connect.name\":\"emp.maersk.com.nextPortCall\"}}],\"connect.name\":\"emp.maersk.co" +
				"m.scheduleEntryIdentifier\"}");
		private emp.maersk.com.vessel _vessel;
		private emp.maersk.com.arrivalVoyage _arrivalVoyage;
		private emp.maersk.com.departureVoyage _departureVoyage;
		private emp.maersk.com.arrivalService _arrivalService;
		private emp.maersk.com.departureService _departureService;
		private emp.maersk.com.previousPortCall _previousPortCall;
		private emp.maersk.com.currentPortCall _currentPortCall;
		private emp.maersk.com.nextPortCall _nextPortCall;
		public virtual Schema Schema
		{
			get
			{
				return scheduleEntryIdentifier._SCHEMA;
			}
		}
		public emp.maersk.com.vessel vessel
		{
			get
			{
				return this._vessel;
			}
			set
			{
				this._vessel = value;
			}
		}
		public emp.maersk.com.arrivalVoyage arrivalVoyage
		{
			get
			{
				return this._arrivalVoyage;
			}
			set
			{
				this._arrivalVoyage = value;
			}
		}
		public emp.maersk.com.departureVoyage departureVoyage
		{
			get
			{
				return this._departureVoyage;
			}
			set
			{
				this._departureVoyage = value;
			}
		}
		public emp.maersk.com.arrivalService arrivalService
		{
			get
			{
				return this._arrivalService;
			}
			set
			{
				this._arrivalService = value;
			}
		}
		public emp.maersk.com.departureService departureService
		{
			get
			{
				return this._departureService;
			}
			set
			{
				this._departureService = value;
			}
		}
		public emp.maersk.com.previousPortCall previousPortCall
		{
			get
			{
				return this._previousPortCall;
			}
			set
			{
				this._previousPortCall = value;
			}
		}
		public emp.maersk.com.currentPortCall currentPortCall
		{
			get
			{
				return this._currentPortCall;
			}
			set
			{
				this._currentPortCall = value;
			}
		}
		public emp.maersk.com.nextPortCall nextPortCall
		{
			get
			{
				return this._nextPortCall;
			}
			set
			{
				this._nextPortCall = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.vessel;
			case 1: return this.arrivalVoyage;
			case 2: return this.departureVoyage;
			case 3: return this.arrivalService;
			case 4: return this.departureService;
			case 5: return this.previousPortCall;
			case 6: return this.currentPortCall;
			case 7: return this.nextPortCall;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.vessel = (emp.maersk.com.vessel)fieldValue; break;
			case 1: this.arrivalVoyage = (emp.maersk.com.arrivalVoyage)fieldValue; break;
			case 2: this.departureVoyage = (emp.maersk.com.departureVoyage)fieldValue; break;
			case 3: this.arrivalService = (emp.maersk.com.arrivalService)fieldValue; break;
			case 4: this.departureService = (emp.maersk.com.departureService)fieldValue; break;
			case 5: this.previousPortCall = (emp.maersk.com.previousPortCall)fieldValue; break;
			case 6: this.currentPortCall = (emp.maersk.com.currentPortCall)fieldValue; break;
			case 7: this.nextPortCall = (emp.maersk.com.nextPortCall)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
