// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace emp.maersk.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class scheduleEntry_record : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"scheduleEntry_record\",\"namespace\":\"emp.maersk.com\",\"fiel" +
				"ds\":[{\"name\":\"rotationId\",\"type\":\"string\"},{\"name\":\"rotationName\",\"type\":\"string" +
				"\"},{\"name\":\"rotationVersion\",\"type\":\"string\"},{\"name\":\"scheduleEntryID\",\"type\":{" +
				"\"type\":\"record\",\"name\":\"scheduleEntryID\",\"namespace\":\"emp.maersk.com\",\"fields\":[" +
				"{\"name\":\"scheduleEntryKey\",\"type\":\"string\"},{\"name\":\"scheduleEntryIdentifier\",\"t" +
				"ype\":{\"type\":\"record\",\"name\":\"scheduleEntryIdentifier\",\"namespace\":\"emp.maersk.c" +
				"om\",\"fields\":[{\"name\":\"vessel\",\"type\":{\"type\":\"record\",\"name\":\"vessel\",\"namespac" +
				"e\":\"emp.maersk.com\",\"fields\":[{\"name\":\"vesselCode\",\"type\":\"string\"},{\"name\":\"IMO" +
				"Number\",\"type\":\"string\"},{\"name\":\"vesselName\",\"type\":\"string\"},{\"name\":\"vesselOp" +
				"eratorCode\",\"type\":\"string\"},{\"name\":\"vesselFlag\",\"type\":\"string\"},{\"name\":\"vess" +
				"elCallSign\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.vessel\"}},{\"name\":\"" +
				"arrivalVoyage\",\"type\":{\"type\":\"record\",\"name\":\"arrivalVoyage\",\"namespace\":\"emp.m" +
				"aersk.com\",\"fields\":[{\"name\":\"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"type" +
				"\":\"string\"}],\"connect.name\":\"emp.maersk.com.arrivalVoyage\"}},{\"name\":\"departureV" +
				"oyage\",\"type\":{\"type\":\"record\",\"name\":\"departureVoyage\",\"namespace\":\"emp.maersk." +
				"com\",\"fields\":[{\"name\":\"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"type\":\"str" +
				"ing\"}],\"connect.name\":\"emp.maersk.com.departureVoyage\"}},{\"name\":\"arrivalService" +
				"\",\"type\":{\"type\":\"record\",\"name\":\"arrivalService\",\"namespace\":\"emp.maersk.com\",\"" +
				"fields\":[{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\"" +
				":\"transportMode\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.arrivalService" +
				"\"}},{\"name\":\"departureService\",\"type\":{\"type\":\"record\",\"name\":\"departureService\"" +
				",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"code\",\"type\":\"string\"},{\"name\":" +
				"\"name\",\"type\":\"string\"},{\"name\":\"transportMode\",\"type\":\"string\"}],\"connect.name\"" +
				":\"emp.maersk.com.departureService\"}},{\"name\":\"previousPortCall\",\"type\":{\"type\":\"" +
				"record\",\"name\":\"previousPortCall\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\"" +
				":\"cityCode\",\"type\":\"string\"},{\"name\":\"terminalCode\",\"type\":\"string\"},{\"name\":\"ci" +
				"tyName\",\"type\":\"string\"},{\"name\":\"terminalName\",\"type\":\"string\"},{\"name\":\"cityGe" +
				"oCode\",\"type\":\"string\"},{\"name\":\"terminalGeoCode\",\"type\":\"string\"},{\"name\":\"prev" +
				"iousScheduleEntryKey\",\"type\":\"string\"},{\"name\":\"arrivalVoyage\",\"type\":\"string\"}," +
				"{\"name\":\"departureVoyage\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.previ" +
				"ousPortCall\"}},{\"name\":\"currentPortCall\",\"type\":{\"type\":\"record\",\"name\":\"current" +
				"PortCall\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"cityCode\",\"type\":\"stri" +
				"ng\"},{\"name\":\"terminalCode\",\"type\":\"string\"},{\"name\":\"cityName\",\"type\":\"string\"}" +
				",{\"name\":\"terminalName\",\"type\":\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"string\"}," +
				"{\"name\":\"terminalGeoCode\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.curre" +
				"ntPortCall\"}},{\"name\":\"nextPortCall\",\"type\":{\"type\":\"record\",\"name\":\"nextPortCal" +
				"l\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"cityCode\",\"type\":\"string\"},{\"" +
				"name\":\"terminalCode\",\"type\":\"string\"},{\"name\":\"cityName\",\"type\":\"string\"},{\"name" +
				"\":\"terminalName\",\"type\":\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"string\"},{\"name\"" +
				":\"terminalGeoCode\",\"type\":\"string\"},{\"name\":\"nextScheduleEntryKey\",\"type\":\"strin" +
				"g\"},{\"name\":\"arrivalVoyage\",\"type\":\"string\"},{\"name\":\"departureVoyage\",\"type\":\"s" +
				"tring\"}],\"connect.name\":\"emp.maersk.com.nextPortCall\"}}],\"connect.name\":\"emp.mae" +
				"rsk.com.scheduleEntryIdentifier\"}}],\"connect.name\":\"emp.maersk.com.scheduleEntry" +
				"ID\"}},{\"name\":\"arrivalStatus\",\"type\":\"string\"},{\"name\":\"departureStatus\",\"type\":" +
				"\"string\"},{\"name\":\"siteCallStatus\",\"type\":\"string\"},{\"name\":\"pH1\",\"type\":\"string" +
				"\"},{\"name\":\"pH2\",\"type\":\"string\"},{\"name\":\"schedule\",\"type\":{\"type\":\"record\",\"na" +
				"me\":\"schedule\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"proformaArrival\"," +
				"\"type\":\"string\"},{\"name\":\"proformaDeparture\",\"type\":\"string\"},{\"name\":\"scheduled" +
				"Arrival\",\"type\":\"string\"},{\"name\":\"scheduledDeparture\",\"type\":\"string\"}],\"connec" +
				"t.name\":\"emp.maersk.com.schedule\"}},{\"name\":\"dummyCall\",\"type\":\"string\"},{\"name\"" +
				":\"omitReason\",\"type\":\"string\"},{\"name\":\"actual\",\"type\":{\"type\":\"record\",\"name\":\"" +
				"actual\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"actualArrival\",\"type\":\"s" +
				"tring\"},{\"name\":\"actualDeparture\",\"type\":\"string\"},{\"name\":\"arrivalAtPilotStatio" +
				"n\",\"type\":\"string\"},{\"name\":\"firstPilotOnBoard\",\"type\":\"string\"},{\"name\":\"pilotO" +
				"ff\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.actual\"}},{\"name\":\"notes\",\"" +
				"type\":\"string\"},{\"name\":\"updatedBy\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk" +
				".com.scheduleEntry_record\"}");
		private string _rotationId;
		private string _rotationName;
		private string _rotationVersion;
		private emp.maersk.com.scheduleEntryID _scheduleEntryID;
		private string _arrivalStatus;
		private string _departureStatus;
		private string _siteCallStatus;
		private string _pH1;
		private string _pH2;
		private emp.maersk.com.schedule _schedule;
		private string _dummyCall;
		private string _omitReason;
		private emp.maersk.com.actual _actual;
		private string _notes;
		private string _updatedBy;
		public virtual Schema Schema
		{
			get
			{
				return scheduleEntry_record._SCHEMA;
			}
		}
		public string rotationId
		{
			get
			{
				return this._rotationId;
			}
			set
			{
				this._rotationId = value;
			}
		}
		public string rotationName
		{
			get
			{
				return this._rotationName;
			}
			set
			{
				this._rotationName = value;
			}
		}
		public string rotationVersion
		{
			get
			{
				return this._rotationVersion;
			}
			set
			{
				this._rotationVersion = value;
			}
		}
		public emp.maersk.com.scheduleEntryID scheduleEntryID
		{
			get
			{
				return this._scheduleEntryID;
			}
			set
			{
				this._scheduleEntryID = value;
			}
		}
		public string arrivalStatus
		{
			get
			{
				return this._arrivalStatus;
			}
			set
			{
				this._arrivalStatus = value;
			}
		}
		public string departureStatus
		{
			get
			{
				return this._departureStatus;
			}
			set
			{
				this._departureStatus = value;
			}
		}
		public string siteCallStatus
		{
			get
			{
				return this._siteCallStatus;
			}
			set
			{
				this._siteCallStatus = value;
			}
		}
		public string pH1
		{
			get
			{
				return this._pH1;
			}
			set
			{
				this._pH1 = value;
			}
		}
		public string pH2
		{
			get
			{
				return this._pH2;
			}
			set
			{
				this._pH2 = value;
			}
		}
		public emp.maersk.com.schedule schedule
		{
			get
			{
				return this._schedule;
			}
			set
			{
				this._schedule = value;
			}
		}
		public string dummyCall
		{
			get
			{
				return this._dummyCall;
			}
			set
			{
				this._dummyCall = value;
			}
		}
		public string omitReason
		{
			get
			{
				return this._omitReason;
			}
			set
			{
				this._omitReason = value;
			}
		}
		public emp.maersk.com.actual actual
		{
			get
			{
				return this._actual;
			}
			set
			{
				this._actual = value;
			}
		}
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				this._notes = value;
			}
		}
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				this._updatedBy = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.rotationId;
			case 1: return this.rotationName;
			case 2: return this.rotationVersion;
			case 3: return this.scheduleEntryID;
			case 4: return this.arrivalStatus;
			case 5: return this.departureStatus;
			case 6: return this.siteCallStatus;
			case 7: return this.pH1;
			case 8: return this.pH2;
			case 9: return this.schedule;
			case 10: return this.dummyCall;
			case 11: return this.omitReason;
			case 12: return this.actual;
			case 13: return this.notes;
			case 14: return this.updatedBy;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.rotationId = (System.String)fieldValue; break;
			case 1: this.rotationName = (System.String)fieldValue; break;
			case 2: this.rotationVersion = (System.String)fieldValue; break;
			case 3: this.scheduleEntryID = (emp.maersk.com.scheduleEntryID)fieldValue; break;
			case 4: this.arrivalStatus = (System.String)fieldValue; break;
			case 5: this.departureStatus = (System.String)fieldValue; break;
			case 6: this.siteCallStatus = (System.String)fieldValue; break;
			case 7: this.pH1 = (System.String)fieldValue; break;
			case 8: this.pH2 = (System.String)fieldValue; break;
			case 9: this.schedule = (emp.maersk.com.schedule)fieldValue; break;
			case 10: this.dummyCall = (System.String)fieldValue; break;
			case 11: this.omitReason = (System.String)fieldValue; break;
			case 12: this.actual = (emp.maersk.com.actual)fieldValue; break;
			case 13: this.notes = (System.String)fieldValue; break;
			case 14: this.updatedBy = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
