// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace emp.maersk.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class scheduleEntries : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"scheduleEntries\",\"namespace\":\"emp.maersk.com\",\"fields\":[" +
				"{\"name\":\"scheduleEntry\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"" +
				"scheduleEntry_record\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"rotationId" +
				"\",\"type\":\"string\"},{\"name\":\"rotationName\",\"type\":\"string\"},{\"name\":\"rotationVers" +
				"ion\",\"type\":\"string\"},{\"name\":\"scheduleEntryID\",\"type\":{\"type\":\"record\",\"name\":\"" +
				"scheduleEntryID\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"scheduleEntryKe" +
				"y\",\"type\":\"string\"},{\"name\":\"scheduleEntryIdentifier\",\"type\":{\"type\":\"record\",\"n" +
				"ame\":\"scheduleEntryIdentifier\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"v" +
				"essel\",\"type\":{\"type\":\"record\",\"name\":\"vessel\",\"namespace\":\"emp.maersk.com\",\"fie" +
				"lds\":[{\"name\":\"vesselCode\",\"type\":\"string\"},{\"name\":\"IMONumber\",\"type\":\"string\"}" +
				",{\"name\":\"vesselName\",\"type\":\"string\"},{\"name\":\"vesselOperatorCode\",\"type\":\"stri" +
				"ng\"},{\"name\":\"vesselFlag\",\"type\":\"string\"},{\"name\":\"vesselCallSign\",\"type\":\"stri" +
				"ng\"}],\"connect.name\":\"emp.maersk.com.vessel\"}},{\"name\":\"arrivalVoyage\",\"type\":{\"" +
				"type\":\"record\",\"name\":\"arrivalVoyage\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"n" +
				"ame\":\"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"type\":\"string\"}],\"connect.na" +
				"me\":\"emp.maersk.com.arrivalVoyage\"}},{\"name\":\"departureVoyage\",\"type\":{\"type\":\"r" +
				"ecord\",\"name\":\"departureVoyage\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"" +
				"voyage\",\"type\":\"string\"},{\"name\":\"direction\",\"type\":\"string\"}],\"connect.name\":\"e" +
				"mp.maersk.com.departureVoyage\"}},{\"name\":\"arrivalService\",\"type\":{\"type\":\"record" +
				"\",\"name\":\"arrivalService\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"code\"," +
				"\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"transportMode\",\"type\":" +
				"\"string\"}],\"connect.name\":\"emp.maersk.com.arrivalService\"}},{\"name\":\"departureSe" +
				"rvice\",\"type\":{\"type\":\"record\",\"name\":\"departureService\",\"namespace\":\"emp.maersk" +
				".com\",\"fields\":[{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"}," +
				"{\"name\":\"transportMode\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.departu" +
				"reService\"}},{\"name\":\"previousPortCall\",\"type\":{\"type\":\"record\",\"name\":\"previous" +
				"PortCall\",\"namespace\":\"emp.maersk.com\",\"fields\":[{\"name\":\"cityCode\",\"type\":\"stri" +
				"ng\"},{\"name\":\"terminalCode\",\"type\":\"string\"},{\"name\":\"cityName\",\"type\":\"string\"}" +
				",{\"name\":\"terminalName\",\"type\":\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"string\"}," +
				"{\"name\":\"terminalGeoCode\",\"type\":\"string\"},{\"name\":\"previousScheduleEntryKey\",\"t" +
				"ype\":\"string\"},{\"name\":\"arrivalVoyage\",\"type\":\"string\"},{\"name\":\"departureVoyage" +
				"\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.previousPortCall\"}},{\"name\":\"" +
				"currentPortCall\",\"type\":{\"type\":\"record\",\"name\":\"currentPortCall\",\"namespace\":\"e" +
				"mp.maersk.com\",\"fields\":[{\"name\":\"cityCode\",\"type\":\"string\"},{\"name\":\"terminalCo" +
				"de\",\"type\":\"string\"},{\"name\":\"cityName\",\"type\":\"string\"},{\"name\":\"terminalName\"," +
				"\"type\":\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"string\"},{\"name\":\"terminalGeoCode" +
				"\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.currentPortCall\"}},{\"name\":\"n" +
				"extPortCall\",\"type\":{\"type\":\"record\",\"name\":\"nextPortCall\",\"namespace\":\"emp.maer" +
				"sk.com\",\"fields\":[{\"name\":\"cityCode\",\"type\":\"string\"},{\"name\":\"terminalCode\",\"ty" +
				"pe\":\"string\"},{\"name\":\"cityName\",\"type\":\"string\"},{\"name\":\"terminalName\",\"type\":" +
				"\"string\"},{\"name\":\"cityGeoCode\",\"type\":\"string\"},{\"name\":\"terminalGeoCode\",\"type" +
				"\":\"string\"},{\"name\":\"nextScheduleEntryKey\",\"type\":\"string\"},{\"name\":\"arrivalVoya" +
				"ge\",\"type\":\"string\"},{\"name\":\"departureVoyage\",\"type\":\"string\"}],\"connect.name\":" +
				"\"emp.maersk.com.nextPortCall\"}}],\"connect.name\":\"emp.maersk.com.scheduleEntryIde" +
				"ntifier\"}}],\"connect.name\":\"emp.maersk.com.scheduleEntryID\"}},{\"name\":\"arrivalSt" +
				"atus\",\"type\":\"string\"},{\"name\":\"departureStatus\",\"type\":\"string\"},{\"name\":\"siteC" +
				"allStatus\",\"type\":\"string\"},{\"name\":\"pH1\",\"type\":\"string\"},{\"name\":\"pH2\",\"type\":" +
				"\"string\"},{\"name\":\"schedule\",\"type\":{\"type\":\"record\",\"name\":\"schedule\",\"namespac" +
				"e\":\"emp.maersk.com\",\"fields\":[{\"name\":\"proformaArrival\",\"type\":\"string\"},{\"name\"" +
				":\"proformaDeparture\",\"type\":\"string\"},{\"name\":\"scheduledArrival\",\"type\":\"string\"" +
				"},{\"name\":\"scheduledDeparture\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com." +
				"schedule\"}},{\"name\":\"dummyCall\",\"type\":\"string\"},{\"name\":\"omitReason\",\"type\":\"st" +
				"ring\"},{\"name\":\"actual\",\"type\":{\"type\":\"record\",\"name\":\"actual\",\"namespace\":\"emp" +
				".maersk.com\",\"fields\":[{\"name\":\"actualArrival\",\"type\":\"string\"},{\"name\":\"actualD" +
				"eparture\",\"type\":\"string\"},{\"name\":\"arrivalAtPilotStation\",\"type\":\"string\"},{\"na" +
				"me\":\"firstPilotOnBoard\",\"type\":\"string\"},{\"name\":\"pilotOff\",\"type\":\"string\"}],\"c" +
				"onnect.name\":\"emp.maersk.com.actual\"}},{\"name\":\"notes\",\"type\":\"string\"},{\"name\":" +
				"\"updatedBy\",\"type\":\"string\"}],\"connect.name\":\"emp.maersk.com.scheduleEntry_recor" +
				"d\"}}}],\"connect.name\":\"emp.maersk.com.scheduleEntries\"}");
		private IList<emp.maersk.com.scheduleEntry_record> _scheduleEntry;
		public virtual Schema Schema
		{
			get
			{
				return scheduleEntries._SCHEMA;
			}
		}
		public IList<emp.maersk.com.scheduleEntry_record> scheduleEntry
		{
			get
			{
				return this._scheduleEntry;
			}
			set
			{
				this._scheduleEntry = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.scheduleEntry;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.scheduleEntry = (IList<emp.maersk.com.scheduleEntry_record>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
