// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace emp.maersk.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class vessel : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""vessel"",""namespace"":""emp.maersk.com"",""fields"":[{""name"":""vesselCode"",""type"":""string""},{""name"":""IMONumber"",""type"":""string""},{""name"":""vesselName"",""type"":""string""},{""name"":""vesselOperatorCode"",""type"":""string""},{""name"":""vesselFlag"",""type"":""string""},{""name"":""vesselCallSign"",""type"":""string""}],""connect.name"":""emp.maersk.com.vessel""}");
		private string _vesselCode;
		private string _IMONumber;
		private string _vesselName;
		private string _vesselOperatorCode;
		private string _vesselFlag;
		private string _vesselCallSign;
		public virtual Schema Schema
		{
			get
			{
				return vessel._SCHEMA;
			}
		}
		public string vesselCode
		{
			get
			{
				return this._vesselCode;
			}
			set
			{
				this._vesselCode = value;
			}
		}
		public string IMONumber
		{
			get
			{
				return this._IMONumber;
			}
			set
			{
				this._IMONumber = value;
			}
		}
		public string vesselName
		{
			get
			{
				return this._vesselName;
			}
			set
			{
				this._vesselName = value;
			}
		}
		public string vesselOperatorCode
		{
			get
			{
				return this._vesselOperatorCode;
			}
			set
			{
				this._vesselOperatorCode = value;
			}
		}
		public string vesselFlag
		{
			get
			{
				return this._vesselFlag;
			}
			set
			{
				this._vesselFlag = value;
			}
		}
		public string vesselCallSign
		{
			get
			{
				return this._vesselCallSign;
			}
			set
			{
				this._vesselCallSign = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.vesselCode;
			case 1: return this.IMONumber;
			case 2: return this.vesselName;
			case 3: return this.vesselOperatorCode;
			case 4: return this.vesselFlag;
			case 5: return this.vesselCallSign;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.vesselCode = (System.String)fieldValue; break;
			case 1: this.IMONumber = (System.String)fieldValue; break;
			case 2: this.vesselName = (System.String)fieldValue; break;
			case 3: this.vesselOperatorCode = (System.String)fieldValue; break;
			case 4: this.vesselFlag = (System.String)fieldValue; break;
			case 5: this.vesselCallSign = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
